[package]
name = "thread-hijacking"
version = "0.1.0"
edition = "2021"


[dependencies]
winapi = {version = "0.3.8", features=[
    "winnt",
    "memoryapi",
    "synchapi",
    "handleapi",
    "errhandlingapi",
    "winbase",
]}